"use client"

import { useEffect, useState } from "react"
import { FaChevronUp } from "react-icons/fa"
import "./globals.css"
import { Footer, Header } from "@/components"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [mobileView, setMobileView] = useState(false)
  const [scrolled, setScrolled] = useState(false)



  useEffect(() => {
    const windowScrollHandler = () => (window.scrollY >= 10 ? setScrolled(true) : setScrolled(false))
    const windowResizeHandler = () => {
      setMobileView(window.innerWidth <= 639)
    }

    window.addEventListener("scroll", windowScrollHandler)
    window.addEventListener("resize", windowResizeHandler)

    return () => {
      window.removeEventListener("resize", windowResizeHandler)
      window.removeEventListener("scroll", windowScrollHandler)
    }
  }, [])

  return (
    <html lang="en">
      <body>
        {/* <img
          className="fixed top-0 left-0 w-full h-auto min-h-[20rem] object-cover opacity-25"
          src="/images/background.png"
          alt=""
        /> */}
        
        {/* <VantaContainer className="text-white overflow-x-hidden bg-black" id="top"> */}
        <div className="text-white overflow-x-hidden bg-black" id="top">
          <Header scrolled={scrolled} mobileView={mobileView} />
          {children}
          <Footer/>
          <a
            href="#top"
            className={`fixed right-8 bottom-12 text-accent bg-white rounded-full shadow-md cursor-pointer z-10 h-12 w-12 flex justify-center items-center duration-[600] transition-transform ease-bounce-down ${
              scrolled ? "scale-100" : "scale-0"
            }`}
          >
            <FaChevronUp />
          </a>

        </div>

        {/* </VantaContainer> */}
      </body>
    </html>
  )
}
